***<center>Name: Aziz ul haq<br>***
Email: azizulhaqprofessional@gmail.com<br>
Github: https://github.com/Azizulhaq-professional/Aziz.AI-ML<br>
Purpose of Document: This is my Porfolio </center>

**Loading Libraries..**

In [2]:
#Install Libraries
%pip install pandas

Requirement already satisfied: pandas in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#importing Libraries
import pandas as pd

**Loading DataSets**

In [7]:
#loading CSV file
pd .read_csv('Data set.csv')

             Name     Design Gender  Age     Salary
0         Mukhtar    Teacher      M  37.0  115000.0
1            Aziz    TEacher      M  30.0    3500.0
2          Mohsin   Engineer      M  29.0    5000.0
3   Naveed Fatima   Analyist      F  30.0    7000.0
4           Babar   Engineer      M  25.0  150000.0
5            Aqsa  Scientist      F  22.0       NaN
6           Rafia   Anaylist      F  29.0    2000.0
7           Samra  Scientist      F  26.0  115000.0
8            Eman   Engineer      F  28.0    3500.0
9        Abdullah    teacher      M  55.0       NaN
10          Mosib  Professor      M  60.0    7000.0
11          Ahmed    Enginer      M   NaN    9000.0
12          Ahsan    Tranier      M  56.0   11000.0
13          Wajid    teacher      M  67.0     200.0
14          Naeem    Trainer      M  80.0    1600.0
15         Qaisar  Professor      M  20.0   17000.0
16          Wajid   Engineer      M  85.0   19000.0

In [8]:
df = pd.read_csv('Data set.csv')

**Preview the Dataset**

In [9]:
print (df)

             Name     Design Gender  Age     Salary
0         Mukhtar    Teacher      M  37.0  115000.0
1            Aziz    TEacher      M  30.0    3500.0
2          Mohsin   Engineer      M  29.0    5000.0
3   Naveed Fatima   Analyist      F  30.0    7000.0
4           Babar   Engineer      M  25.0  150000.0
5            Aqsa  Scientist      F  22.0       NaN
6           Rafia   Anaylist      F  29.0    2000.0
7           Samra  Scientist      F  26.0  115000.0
8            Eman   Engineer      F  28.0    3500.0
9        Abdullah    teacher      M  55.0       NaN
10          Mosib  Professor      M  60.0    7000.0
11          Ahmed    Enginer      M   NaN    9000.0
12          Ahsan    Tranier      M  56.0   11000.0
13          Wajid    teacher      M  67.0     200.0
14          Naeem    Trainer      M  80.0    1600.0
15         Qaisar  Professor      M  20.0   17000.0
16          Wajid   Engineer      M  85.0   19000.0

In [10]:
#Install Excel Libraries
%pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\aziz ul haq\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
pd . read_excel ('Data set.xlsx')

             Name     Design Gender  Age     Salary
0         Mukhtar    Teacher      M  37.0  115000.0
1            Aziz    TEacher      M  30.0    3500.0
2          Mohsin   Engineer      M  29.0    5000.0
3   Naveed Fatima   Analyist      F  30.0    7000.0
4           Babar   Engineer      M  25.0  150000.0
5            Aqsa  Scientist      F  22.0       NaN
6           Rafia   Anaylist      F  29.0    2000.0
7           Samra  Scientist      F  26.0  115000.0
8            Eman   Engineer      F  28.0    3500.0
9        Abdullah    teacher      M  55.0       NaN
10          Mosib  Professor      M  60.0    7000.0
11          Ahmed    Enginer      M   NaN    9000.0
12          Ahsan    Tranier      M  56.0   11000.0
13          Wajid    teacher      M  67.0     200.0
14          Naeem    Trainer      M  80.0    1600.0
15         Qaisar  Professor      M  20.0   17000.0
16          Wajid   Engineer      M  85.0   19000.0

In [15]:
df.head(2)

      Name   Design Gender  Age     Salary
0  Mukhtar  Teacher      M  37.0  115000.0
1     Aziz  TEacher      M  30.0    3500.0

In [19]:
df.tail(3)

      Name     Design Gender  Age    Salary
14   Naeem    Trainer      M  80.0   1600.0
15  Qaisar  Professor      M  20.0  17000.0
16   Wajid   Engineer      M  85.0  19000.0

In [22]:
df.head(5)

            Name    Design Gender  Age     Salary
0        Mukhtar   Teacher      M  37.0  115000.0
1           Aziz   TEacher      M  30.0    3500.0
2         Mohsin  Engineer      M  29.0    5000.0
3  Naveed Fatima  Analyist      F  30.0    7000.0
4          Babar  Engineer      M  25.0  150000.0

In [23]:
df.head()

            Name    Design Gender  Age     Salary
0        Mukhtar   Teacher      M  37.0  115000.0
1           Aziz   TEacher      M  30.0    3500.0
2         Mohsin  Engineer      M  29.0    5000.0
3  Naveed Fatima  Analyist      F  30.0    7000.0
4          Babar  Engineer      M  25.0  150000.0

In [24]:
df.loc[2]

Name        Mohsin
Design    Engineer
Gender           M
Age           29.0
Salary      5000.0
Name: 2, dtype: object

In [25]:
df.loc[2:5]

            Name     Design Gender  Age     Salary
2         Mohsin   Engineer      M  29.0    5000.0
3  Naveed Fatima   Analyist      F  30.0    7000.0
4          Babar   Engineer      M  25.0  150000.0
5           Aqsa  Scientist      F  22.0       NaN

In [26]:
df.loc[8:8]

   Name    Design Gender  Age   Salary
8  Eman  Engineer      F  28.0  3500.0