In [ ]:
# install Pandas
%pip install pandas
import pandas as pd

%pip insertall numpy
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
ERROR: unknown command "insertall" - maybe you meant "install"

Basic data structures in pandas

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
# Creating a Series by passing a list of values, letting pandas create a default RangeIndex.
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.897262  1.384550 -1.182905  1.929158
2013-01-02 -0.859996 -1.187251  0.182544 -0.624786
2013-01-03 -0.060014  0.178804  2.459899  1.289818
2013-01-04 -0.025104  0.195106  1.221054 -1.382464
2013-01-05  1.462782  0.832367  0.136026  2.121461
2013-01-06 -0.751031 -1.135373 -1.092513 -0.284031

In [ ]:
# Creating a DataFrame by passing a dictionary of objects where the keys are the column labels and the values are the column values.
df2 = pd.DataFrame(

    {

        "A": 1.0,

        "B": pd.Timestamp("20130102"),

        "C": pd.Series(1, index=list(range(4)), dtype="float32"),

        "D": np.array([3] * 4, dtype="int32"),

        "E": pd.Categorical(["test", "train", "test", "train"]),

        "F": "foo",

    }

)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
# The columns of the resulting DataFrame have different dtypes:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
In [12]: df2.   # noqa: E225, E999
df2.A                  df2.bool
df2.abs                df2.boxplot
df2.add                df2.C
df2.add_prefix         df2.clip
df2.add_suffix         df2.columns
df2.align              df2.copy
df2.all                df2.count
df2.any                df2.combine
df2.append             df2.D
df2.apply              df2.describe
df2.applymap           df2.diff
df2.B                  df2.duplicated

SyntaxError: invalid syntax (<ipython-input-10-6c1592db3b3a>, line 1)

# Viewing data

In [ ]:
# Use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:
df.head()

                   A         B         C         D
2013-01-01 -0.897262  1.384550 -1.182905  1.929158
2013-01-02 -0.859996 -1.187251  0.182544 -0.624786
2013-01-03 -0.060014  0.178804  2.459899  1.289818
2013-01-04 -0.025104  0.195106  1.221054 -1.382464
2013-01-05  1.462782  0.832367  0.136026  2.121461

In [ ]:
df.tail(3)

                   A         B         C         D
2013-01-04 -0.025104  0.195106  1.221054 -1.382464
2013-01-05  1.462782  0.832367  0.136026  2.121461
2013-01-06 -0.751031 -1.135373 -1.092513 -0.284031

In [ ]:
# Display the DataFrame.index or DataFrame.columns:
df.index

In [ ]:
df.columns

In [ ]:
# Return a NumPy representation of the underlying data with DataFrame.to_numpy() without the index or column labels:
df.to_numpy()

In [ ]:
# NumPy arrays have one dtype for the entire array while pandas DataFrames have one dtype per column. When you call DataFrame.to_numpy(), pandas will find the NumPy dtype that can hold all of the dtypes in the DataFrame. If the common data type is object, DataFrame.to_numpy() will require copying data.
df2.dtypes

In [ ]:
df2.to_numpy()

In [ ]:
# describe() shows a quick statistic summary of your data:
df.describe()

In [ ]:
# Transposing your data:
df.T

In [ ]:
# DataFrame.sort_index() sorts by an axis:
df.sort_index(axis=1, ascending=False)

In [ ]:
# DataFrame.sort_values() sorts by values:
df.sort_values(by="B")

Selection