<center style="color: red">Name: Hassan Abbas <br></center><br>
<center style="color:yellow">Email: hassanabbasaiengineer@gmail.com<br></center><br>
<center style="color:green">Github:https://github.com/HassanEng118<br>
Purpose of Documents: For implementation a small datasets</center>

In [3]:
# loading libraries
%pip install pandas

Requirement already satisfied: pandas in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hassa\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\hassa\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
#importing library
import pandas as pd

# **loading datasets**

In [8]:
#loading csv files
pd.read_csv("data.csv")

             Name Designation  Gender     Age     Salary
0         Mukhtar   professor        M   37.0   115000.0
1            Aziz      Teacher       M   30.0    35000.0
2          Mohsin     Engineer       M   29.0    50000.0
3   Naveed Fatima     Analyst        F   30.0    70000.0
4           Babar     Engineer       M   25.0  1500000.0
5            Aqsa     Scienist       F   22.0        NaN
6           Rafia     Analyst        F   29.0    20000.0
7           Samra    Scientist       F   26.0   115000.0
8            Eman     Engineer       F   28.0    35000.0
9        Abdullah      Teacher       M   55.0        NaN
10          Mosib   professor        M   60.0        NaN
11          Ahmed     engineer       M    NaN        NaN
12          Ahsan      trainer       M  156.0    90000.0
13          Wajid      teacher       M   67.0   110000.0
14          Naeen      trainer       M   80.0    16000.0
15         Qaisar   professor        M   20.0   170000.0
16          Wajid     Engineer       M   85.0   190000.0

In [11]:
df=pd.read_csv("data.csv")

In [12]:
print(df)

             Name Designation  Gender     Age     Salary
0         Mukhtar   professor        M   37.0   115000.0
1            Aziz      Teacher       M   30.0    35000.0
2          Mohsin     Engineer       M   29.0    50000.0
3   Naveed Fatima     Analyst        F   30.0    70000.0
4           Babar     Engineer       M   25.0  1500000.0
5            Aqsa     Scienist       F   22.0        NaN
6           Rafia     Analyst        F   29.0    20000.0
7           Samra    Scientist       F   26.0   115000.0
8            Eman     Engineer       F   28.0    35000.0
9        Abdullah      Teacher       M   55.0        NaN
10          Mosib   professor        M   60.0        NaN
11          Ahmed     engineer       M    NaN        NaN
12          Ahsan      trainer       M  156.0    90000.0
13          Wajid      teacher       M   67.0   110000.0
14          Naeen      trainer       M   80.0    16000.0
15         Qaisar   professor        M   20.0   170000.0
16          Wajid     Engineer       M   85.0   190000.0

In [13]:
df

             Name Designation  Gender     Age     Salary
0         Mukhtar   professor        M   37.0   115000.0
1            Aziz      Teacher       M   30.0    35000.0
2          Mohsin     Engineer       M   29.0    50000.0
3   Naveed Fatima     Analyst        F   30.0    70000.0
4           Babar     Engineer       M   25.0  1500000.0
5            Aqsa     Scienist       F   22.0        NaN
6           Rafia     Analyst        F   29.0    20000.0
7           Samra    Scientist       F   26.0   115000.0
8            Eman     Engineer       F   28.0    35000.0
9        Abdullah      Teacher       M   55.0        NaN
10          Mosib   professor        M   60.0        NaN
11          Ahmed     engineer       M    NaN        NaN
12          Ahsan      trainer       M  156.0    90000.0
13          Wajid      teacher       M   67.0   110000.0
14          Naeen      trainer       M   80.0    16000.0
15         Qaisar   professor        M   20.0   170000.0
16          Wajid     Engineer       M   85.0   190000.0

In [14]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hassa\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in c:\users\hassa\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\hassa\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
pd.read_excel("data.xlsx")

             Name Designation  Gender     Age     Salary
0         Mukhtar   professor        M   37.0    11500.0
1            Aziz      Teacher       M   30.0    35000.0
2          Mohsin     Engineer       M   29.0    50000.0
3   Naveed Fatima     Analyst        F   30.0    70000.0
4           Babar     Engineer       M   25.0  1500000.0
5            Aqsa     Scienist       F   22.0        NaN
6           Rafia     Analyst        F   29.0    20000.0
7           Samra    Scientist       F   26.0   115000.0
8            Eman     Engineer       F   28.0    35000.0
9        Abdullah      Teacher       M   55.0        NaN
10          Mosib   professor        M   60.0        NaN
11          Ahmed     engineer       M    NaN        NaN
12          Ahsan      trainer       M  156.0        NaN
13          Wajid      teacher       M   67.0        NaN
14          Naeen      trainer       M   80.0        NaN
15         Qaisar   professor        M   20.0        NaN
16          Wajid     Engineer       M   85.0        NaN

In [16]:
df.head()

            Name Designation  Gender    Age     Salary
0        Mukhtar   professor        M  37.0   115000.0
1           Aziz      Teacher       M  30.0    35000.0
2         Mohsin     Engineer       M  29.0    50000.0
3  Naveed Fatima     Analyst        F  30.0    70000.0
4          Babar     Engineer       M  25.0  1500000.0

In [17]:
df.dead(1)

AttributeError: 'DataFrame' object has no attribute 'dead'

In [18]:
df.head(1)

      Name Designation  Gender    Age    Salary
0  Mukhtar   professor        M  37.0  115000.0

In [19]:
df.tail()

      Name Designation  Gender     Age    Salary
12   Ahsan      trainer       M  156.0   90000.0
13   Wajid      teacher       M   67.0  110000.0
14   Naeen      trainer       M   80.0   16000.0
15  Qaisar   professor        M   20.0  170000.0
16   Wajid     Engineer       M   85.0  190000.0

In [20]:
df.tail(2)

      Name Designation  Gender    Age    Salary
15  Qaisar   professor        M  20.0  170000.0
16   Wajid     Engineer       M  85.0  190000.0

In [21]:
df.between_time()

TypeError: NDFrame.between_time() missing 2 required positional arguments: 'start_time' and 'end_time'

In [22]:
df.iloc(10:12)

SyntaxError: invalid syntax (1068061253.py, line 1)

In [23]:
df.iloc(9)

ValueError: No axis named 9 for object type DataFrame

In [24]:
df.iloc [10:12]

     Name Designation  Gender    Age  Salary
10  Mosib   professor        M  60.0     NaN
11  Ahmed     engineer       M   NaN     NaN

In [25]:
df.iloc[10]

Name                 Mosib
Designation     professor
Gender                   M
Age                   60.0
Salary                 NaN
Name: 10, dtype: object