In [1]:
import pandas 
import pandas as pd
pd.read_csv("data2.csv")

         Days  phy  MATH  CHEM  TOTAL
0      Monday   56    52    76    184
1     Tuesday   64    96    60    220
2   Wednesday   36    63    70    169
3    Thursday    9    11    32     52
4      Friday   69   100    94    263
5    Saturday    3    99    88    190
6      Sunday    0    39    30     69
7      Monday   20    96    60    176
8     Tuesday   13    89    61    163
9   Wednesday   82    49    76    207
10   Thursday   78    44    52    174
11     Friday   97    26    45    168
12   Saturday   49    70    86    205
13     Sunday   57    99    31    187
14     Monday   15    37    88    140
15    Tuesday  100    33    81    214
16  Wednesday  100    20    47    167

In [2]:
df=pd.read_csv("data2.csv")
print(df)

         Days  phy  MATH  CHEM  TOTAL
0      Monday   56    52    76    184
1     Tuesday   64    96    60    220
2   Wednesday   36    63    70    169
3    Thursday    9    11    32     52
4      Friday   69   100    94    263
5    Saturday    3    99    88    190
6      Sunday    0    39    30     69
7      Monday   20    96    60    176
8     Tuesday   13    89    61    163
9   Wednesday   82    49    76    207
10   Thursday   78    44    52    174
11     Friday   97    26    45    168
12   Saturday   49    70    86    205
13     Sunday   57    99    31    187
14     Monday   15    37    88    140
15    Tuesday  100    33    81    214
16  Wednesday  100    20    47    167

In [3]:
df.describe()

              phy        MATH       CHEM       TOTAL
count   17.000000   17.000000  17.000000   17.000000
mean    49.882353   60.176471  63.352941  173.411765
std     35.124568   31.105135  21.280687   50.932626
min      0.000000   11.000000  30.000000   52.000000
25%     15.000000   37.000000  47.000000  167.000000
50%     56.000000   52.000000  61.000000  176.000000
75%     78.000000   96.000000  81.000000  205.000000
max    100.000000  100.000000  94.000000  263.000000

In [5]:
df.shape

(17, 5)

In [8]:
printdata=pd.read_csv("data2.csv")
print("printdata")

printdata

In [7]:
print("printdata")

printdata

In [9]:
df.shape

(17, 5)

In [11]:
df['Designation']

KeyError: 'Designation'

In [12]:
df.isnull().sum()

Days     0
phy      0
MATH     0
CHEM     0
TOTAL    0
dtype: int64

In [13]:
df['age'].isnull().sum()

KeyError: 'age'

In [14]:
df['phy'].isnull().sum()

np.int64(0)

In [18]:
#replacing null value
df['phy']=df['phy'].fillna(df['phy'].median())

In [17]:
df['phy'].isnull().sum()

np.int64(0)

In [3]:
import pandas as pd
pd.read_csv("data2.csv")

         Days    phy  MATH  CHEM  TOTAL
0      Monday    NaN    52    76    184
1     Tuesday   64.0    96    60    220
2   Wednesday   36.0    63    70    169
3    Thursday    9.0    11    32     52
4      Friday   69.0   100    94    263
5    Saturday    3.0    99    88    190
6      Sunday    0.0    39    30     69
7      Monday   20.0    96    60    176
8     Tuesday   13.0    89    61    163
9   Wednesday   82.0    49    76    207
10   Thursday    NaN    44    52    174
11     Friday   97.0    26    45    168
12   Saturday   49.0    70    86    205
13     Sunday   57.0    99    31    187
14     Monday   15.0    37    88    140
15    Tuesday  100.0    33    81    214
16  Wednesday  100.0    20    47    167

In [4]:
pd.describe()

AttributeError: module 'pandas' has no attribute 'describe'

In [7]:
df=pd.read_csv('data2.csv')
df.describe()

              phy        MATH       CHEM       TOTAL
count   15.000000   17.000000  17.000000   17.000000
mean    47.600000   60.176471  63.352941  173.411765
std     36.677747   31.105135  21.280687   50.932626
min      0.000000   11.000000  30.000000   52.000000
25%     14.000000   37.000000  47.000000  167.000000
50%     49.000000   52.000000  61.000000  176.000000
75%     75.500000   96.000000  81.000000  205.000000
max    100.000000  100.000000  94.000000  263.000000

In [9]:
df['designation']

KeyError: 'designation'