<center>

**Name** : Muahammad Talha Nazeer <br>

**Email** : talhanazeer2001@gmail.com<br>

**GitHub** : https://github.com/talha-nazeer <br>

**Purpose of Document** : Train Model on Dataset <br> 

</center>

In [1]:
#Importing Libraries
import pandas as pd

In [3]:
#loading CSV file
pd.read_csv("DATA.CSV")

             Name Designation Gender    Age     Salary
0         Mukhtar   Professor      M   37.0   115000.0
1           Azziz     Teacher      M   30.0    35000.0
2          Mohsin    Engineer      M   29.0    50000.0
3   Naveed Fatima     Analyst      F   30.0    70000.0
4           Babar    Engineer      M   25.0  1500000.0
5            Aqsa   Scientist      F   22.0        NaN
6           Rafia     Analyst      F   29.0    20000.0
7           Samra   Scientist      F   26.0   115000.0
8            Eman    Engineer      F   28.0    35000.0
9        Abdullah     Teacher      M   55.0        NaN
10          Mosib   Professor      M   60.0    70000.0
11          Ahmad    Engineer      M    NaN    90000.0
12          Ahsan     trainer      M  156.0   110000.0
13          Wajid     Teacher      M   67.0     2000.0
14         Naseem     trainer      M   80.0    16000.0
15         Qaiser   Professor      M   20.0   170000.0
16          Wajid    Engineer      M   85.0   190000.0

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df

             Name Designation Gender    Age     Salary
0         Mukhtar   Professor      M   37.0   115000.0
1           Azziz     Teacher      M   30.0    35000.0
2          Mohsin    Engineer      M   29.0    50000.0
3   Naveed Fatima     Analyst      F   30.0    70000.0
4           Babar    Engineer      M   25.0  1500000.0
5            Aqsa   Scientist      F   22.0        NaN
6           Rafia     Analyst      F   29.0    20000.0
7           Samra   Scientist      F   26.0   115000.0
8            Eman    Engineer      F   28.0    35000.0
9        Abdullah     Teacher      M   55.0        NaN
10          Mosib   Professor      M   60.0    70000.0
11          Ahmad    Engineer      M    NaN    90000.0
12          Ahsan     trainer      M  156.0   110000.0
13          Wajid     Teacher      M   67.0     2000.0
14         Naseem     trainer      M   80.0    16000.0
15         Qaiser   Professor      M   20.0   170000.0
16          Wajid    Engineer      M   85.0   190000.0

In [6]:
#install Excel Libraries
%pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pd.read_excel('data.xlsx')

       Name Designation  Gender  Age  Salary
0   Charlie     Manager    Male   23   78523
1      Paul    Engineer    Male   30   63332
2    Quincy     Analyst  Female   29  110424
3       Bob     Manager    Male   32   31536
4    George       Clerk    Male   49   55219
5    Edward  Technician    Male   25   30683
6     Irene  Technician  Female   54   65454
7     Alice  Technician    Male   46  106580
8      Liam    Engineer    Male   30   84381
9      Mona     Manager  Female   59   50349
10   Rachel       Clerk  Female   34   46706
11    Diana    Engineer    Male   26   38020
12     Jack       Clerk  Female   55   60933
13   Olivia       Clerk  Female   22   33221
14    Fiona  Technician  Female   24   54126
15   Hannah     Manager  Female   59   89088
16   Nathan    Engineer    Male   40   36436
17    Karen  Technician    Male   29  107164

In [8]:
#display the top rows

df.head()

            Name Designation Gender   Age     Salary
0        Mukhtar   Professor      M  37.0   115000.0
1          Azziz     Teacher      M  30.0    35000.0
2         Mohsin    Engineer      M  29.0    50000.0
3  Naveed Fatima     Analyst      F  30.0    70000.0
4          Babar    Engineer      M  25.0  1500000.0

In [9]:
#display first row
df.head(1)

      Name Designation Gender   Age    Salary
0  Mukhtar   Professor      M  37.0  115000.0

In [10]:
#display bottom rows
df.tail()

      Name Designation Gender    Age    Salary
12   Ahsan     trainer      M  156.0  110000.0
13   Wajid     Teacher      M   67.0    2000.0
14  Naseem     trainer      M   80.0   16000.0
15  Qaiser   Professor      M   20.0  170000.0
16   Wajid    Engineer      M   85.0  190000.0

In [11]:
#display last 2 rows
df.tail(2)

      Name Designation Gender   Age    Salary
15  Qaiser   Professor      M  20.0  170000.0
16   Wajid    Engineer      M  85.0  190000.0

In [12]:
#display row 8,9 from middle
df.loc[8:9]

       Name Designation Gender   Age   Salary
8      Eman    Engineer      F  28.0  35000.0
9  Abdullah     Teacher      M  55.0      NaN

In [13]:
#Install Doxc libraries
%pip install python-docx

Requirement already satisfied: python-docx in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: lxml>=3.1.0 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing-extensions>=4.9.0 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (from python-docx) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [14]:
from docx import Document

In [16]:
document=Document("talhaword.docx")

In [17]:
document.paragraphs[0].text

'My name is Talha'

In [18]:
#Install PDF libraries
%pip install PyPDF2

Requirement already satisfied: PyPDF2 in c:\users\talha nazeer ai&ml\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from PyPDF2 import PdfFileReader

In [21]:
from PyPDF2 import PdfReader

In [24]:
pdf= PdfReader("talhaword.pdf")

In [25]:
txt=pdf.pages[0]

In [26]:
txt.extract_text()

'My name is Talha  \n '

In [27]:
#JSON files

In [28]:
import json

In [33]:
a=open("talha.json", "r")
data= a.read()